---
- become: true
  name: Converge
  hosts: all
  roles:
    - role: ansible-role-nodejs-toolchain
      vars:
        nodejs_toolchain_version: testting_nodejs_version
        nodejs_toolchain_url: https://ansible-molecule-test.s3.amazonaws.com/test_nodejstoolchain.tar.gz
